version: '3.4'

services:
  mysql:
    image: mysql:5.7
    ports:
        - 3309:3309
    volumes:
        - /var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: gestion
        MYSQL_USER: gestion
        MYSQL_PASSWORD: gestion
        MYSQL_DATABASE: gestion
  nginx:
    image: nginx:alpine
    ports:
      - 1314:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/gestion

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/gestion

  memcached:
    container_name: mymemcached
    image: memcached:latest
    ports:
      - "11211:11211"
      